name: Custom Offline

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build Tag'
        required: true
        default: 'dev'
      version:
        description: 'Release Version'
        required: true
        default: 'v4-dev'

env:
  tag: ${{ github.event.inputs.tag }}
  version: ${{ github.event.inputs.version }}
  image_tag: ${{ github.event.inputs.version }}-ce

jobs:
  offline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ 'x86_64', 'aarch64', 'ppc64le', 's390x' ]
    steps:
      - name: Prepare installer
        run: |
          mkdir -p dist
          git clone -b ${{ env.tag }} --depth=1 https://github.com/jumpserver/installer.git
          rm -rf installer/hudson.* installer/.travis.yml installer/.git installer/.github
          sed -i "s@VERSION=.*@VERSION=${{ env.image_tag }}@g" installer/static.env
          sed -i "s@VERSION=.*@VERSION=${{ env.tag }}@g" installer/quick_start.sh installer/cn-quick_start.sh
          sed -i "s@redis:7.0-bullseye@redis:7-bookworm@g" installer/scripts/utils.sh installer/compose/redis.yml
          sed -i "s@postgres:16.3-bullseye@postgres:16-bookworm@g" installer/scripts/utils.sh installer/compose/postgres.yml
          cp -R installer jumpserver-installer-${{ env.version }}
          cp -R installer jumpserver-ce-${{ env.version }}-${{ matrix.architecture }}
          sudo tar -zcvf dist/jumpserver-installer-${{ env.version }}.tar.gz jumpserver-installer-${{ env.version }}

      - name: Prepare images
        run: |
          case ${{ matrix.architecture }} in
            x86_64)
              platform=linux/amd64
              ;;
            aarch64)
              platform=linux/arm64
              ;;
            ppc64le)
              platform=linux/ppc64le
              ;;
            s390x)
              platform=linux/s390x
              ;;
          esac

          apps="core koko lion chen web"
          for image_name in $apps; do
            docker pull --platform=${platform} ghcr.io/${{ github.repository_owner }}/${image_name}:${{ env.image_tag }}
            docker tag ghcr.io/${{ github.repository_owner }}/${image_name}:${{ env.image_tag }} jumpserver/${image_name}:${{ env.image_tag }}
            docker rmi -f ghcr.io/${{ github.repository_owner }}/${image_name}:${{ env.image_tag }}
          done
          docker pull --platform=${platform} redis:7-bookworm
          docker pull --platform=${platform} postgres:16-bookworm
          docker images

      - name: Build offline
        run: |
          cd jumpserver-ce-${{ env.version }}-${{ matrix.architecture }}/scripts
          sudo -E bash -ex ./0_prepare.sh run
          cd ../../
          sudo tar -czf dist/jumpserver-ce-${{ env.version }}-${{ matrix.architecture }}.tar.gz jumpserver-ce-${{ env.version }}-${{ matrix.architecture }}
        env:
          BUILD_ARCH: ${{ matrix.architecture }}

      - name: Upload offline
        run: |
          gh release upload ${{ env.version }} dist/*.tar.gz -R ${{ github.repository }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}